// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hero.proto

package proto;

public final class Hero {
  private Hero() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBHeroEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PBHeroEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 hero_id = 1;</code>
     */
    long getHeroId();

    /**
     * <code>optional int32 conf_id = 2;</code>
     */
    int getConfId();

    /**
     * <code>optional int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>optional int32 break_level = 4;</code>
     */
    int getBreakLevel();

    /**
     * <code>optional int32 exp = 5;</code>
     */
    int getExp();

    /**
     * <code>repeated int32 awake_info = 6;</code>
     */
    java.util.List<Integer> getAwakeInfoList();
    /**
     * <code>repeated int32 awake_info = 6;</code>
     */
    int getAwakeInfoCount();
    /**
     * <code>repeated int32 awake_info = 6;</code>
     */
    int getAwakeInfo(int index);

    /**
     * <code>optional int32 awake_level = 7;</code>
     */
    int getAwakeLevel();

    /**
     * <code>optional int32 tianming_level = 8;</code>
     */
    int getTianmingLevel();

    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */
    int getAttributesCount();
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */
    boolean containsAttributes(
            int key);
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @Deprecated
    java.util.Map<Integer, Integer>
    getAttributes();
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */
    java.util.Map<Integer, Integer>
    getAttributesMap();
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */

    int getAttributesOrDefault(
            int key,
            int defaultValue);
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */

    int getAttributesOrThrow(
            int key);
  }
  /**
   * Protobuf type {@code proto.PBHeroEntity}
   */
  public  static final class PBHeroEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PBHeroEntity)
      PBHeroEntityOrBuilder {
    // Use PBHeroEntity.newBuilder() to construct.
    private PBHeroEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBHeroEntity() {
      heroId_ = 0L;
      confId_ = 0;
      level_ = 0;
      breakLevel_ = 0;
      exp_ = 0;
      awakeInfo_ = java.util.Collections.emptyList();
      awakeLevel_ = 0;
      tianmingLevel_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBHeroEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              heroId_ = input.readInt64();
              break;
            }
            case 16: {

              confId_ = input.readInt32();
              break;
            }
            case 24: {

              level_ = input.readInt32();
              break;
            }
            case 32: {

              breakLevel_ = input.readInt32();
              break;
            }
            case 40: {

              exp_ = input.readInt32();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                awakeInfo_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              awakeInfo_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                awakeInfo_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                awakeInfo_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {

              awakeLevel_ = input.readInt32();
              break;
            }
            case 64: {

              tianmingLevel_ = input.readInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                attributes_ = com.google.protobuf.MapField.newMapField(
                    AttributesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000100;
              }
              com.google.protobuf.MapEntry<Integer, Integer>
              attributes__ = input.readMessage(
                  AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attributes_.getMutableMap().put(
                  attributes__.getKey(), attributes__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          awakeInfo_ = java.util.Collections.unmodifiableList(awakeInfo_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Hero.internal_static_proto_PBHeroEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 9:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Hero.internal_static_proto_PBHeroEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBHeroEntity.class, Builder.class);
    }

    private int bitField0_;
    public static final int HERO_ID_FIELD_NUMBER = 1;
    private long heroId_;
    /**
     * <code>optional int64 hero_id = 1;</code>
     */
    public long getHeroId() {
      return heroId_;
    }

    public static final int CONF_ID_FIELD_NUMBER = 2;
    private int confId_;
    /**
     * <code>optional int32 conf_id = 2;</code>
     */
    public int getConfId() {
      return confId_;
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>optional int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int BREAK_LEVEL_FIELD_NUMBER = 4;
    private int breakLevel_;
    /**
     * <code>optional int32 break_level = 4;</code>
     */
    public int getBreakLevel() {
      return breakLevel_;
    }

    public static final int EXP_FIELD_NUMBER = 5;
    private int exp_;
    /**
     * <code>optional int32 exp = 5;</code>
     */
    public int getExp() {
      return exp_;
    }

    public static final int AWAKE_INFO_FIELD_NUMBER = 6;
    private java.util.List<Integer> awakeInfo_;
    /**
     * <code>repeated int32 awake_info = 6;</code>
     */
    public java.util.List<Integer>
        getAwakeInfoList() {
      return awakeInfo_;
    }
    /**
     * <code>repeated int32 awake_info = 6;</code>
     */
    public int getAwakeInfoCount() {
      return awakeInfo_.size();
    }
    /**
     * <code>repeated int32 awake_info = 6;</code>
     */
    public int getAwakeInfo(int index) {
      return awakeInfo_.get(index);
    }
    private int awakeInfoMemoizedSerializedSize = -1;

    public static final int AWAKE_LEVEL_FIELD_NUMBER = 7;
    private int awakeLevel_;
    /**
     * <code>optional int32 awake_level = 7;</code>
     */
    public int getAwakeLevel() {
      return awakeLevel_;
    }

    public static final int TIANMING_LEVEL_FIELD_NUMBER = 8;
    private int tianmingLevel_;
    /**
     * <code>optional int32 tianming_level = 8;</code>
     */
    public int getTianmingLevel() {
      return tianmingLevel_;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 9;
    private static final class AttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          Integer, Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<Integer, Integer>newDefaultInstance(
                  Hero.internal_static_proto_PBHeroEntity_AttributesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        Integer, Integer> attributes_;
    private com.google.protobuf.MapField<Integer, Integer>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */

    public boolean containsAttributes(
        int key) {
      
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @Deprecated
    public java.util.Map<Integer, Integer> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */

    public java.util.Map<Integer, Integer> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */

    public int getAttributesOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<Integer, Integer> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; attributes = 9;</code>
     */

    public int getAttributesOrThrow(
        int key) {
      
      java.util.Map<Integer, Integer> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (heroId_ != 0L) {
        output.writeInt64(1, heroId_);
      }
      if (confId_ != 0) {
        output.writeInt32(2, confId_);
      }
      if (level_ != 0) {
        output.writeInt32(3, level_);
      }
      if (breakLevel_ != 0) {
        output.writeInt32(4, breakLevel_);
      }
      if (exp_ != 0) {
        output.writeInt32(5, exp_);
      }
      if (getAwakeInfoList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(awakeInfoMemoizedSerializedSize);
      }
      for (int i = 0; i < awakeInfo_.size(); i++) {
        output.writeInt32NoTag(awakeInfo_.get(i));
      }
      if (awakeLevel_ != 0) {
        output.writeInt32(7, awakeLevel_);
      }
      if (tianmingLevel_ != 0) {
        output.writeInt32(8, tianmingLevel_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetAttributes(),
          AttributesDefaultEntryHolder.defaultEntry,
          9);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (heroId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, heroId_);
      }
      if (confId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, confId_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (breakLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, breakLevel_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, exp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < awakeInfo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(awakeInfo_.get(i));
        }
        size += dataSize;
        if (!getAwakeInfoList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        awakeInfoMemoizedSerializedSize = dataSize;
      }
      if (awakeLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, awakeLevel_);
      }
      if (tianmingLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, tianmingLevel_);
      }
      for (java.util.Map.Entry<Integer, Integer> entry
           : internalGetAttributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<Integer, Integer>
        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(9, attributes__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBHeroEntity)) {
        return super.equals(obj);
      }
      PBHeroEntity other = (PBHeroEntity) obj;

      boolean result = true;
      result = result && (getHeroId()
          == other.getHeroId());
      result = result && (getConfId()
          == other.getConfId());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (getBreakLevel()
          == other.getBreakLevel());
      result = result && (getExp()
          == other.getExp());
      result = result && getAwakeInfoList()
          .equals(other.getAwakeInfoList());
      result = result && (getAwakeLevel()
          == other.getAwakeLevel());
      result = result && (getTianmingLevel()
          == other.getTianmingLevel());
      result = result && internalGetAttributes().equals(
          other.internalGetAttributes());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HERO_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeroId());
      hash = (37 * hash) + CONF_ID_FIELD_NUMBER;
      hash = (53 * hash) + getConfId();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + BREAK_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getBreakLevel();
      hash = (37 * hash) + EXP_FIELD_NUMBER;
      hash = (53 * hash) + getExp();
      if (getAwakeInfoCount() > 0) {
        hash = (37 * hash) + AWAKE_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getAwakeInfoList().hashCode();
      }
      hash = (37 * hash) + AWAKE_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getAwakeLevel();
      hash = (37 * hash) + TIANMING_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getTianmingLevel();
      if (!internalGetAttributes().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttributes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBHeroEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBHeroEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBHeroEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBHeroEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBHeroEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBHeroEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBHeroEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBHeroEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBHeroEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBHeroEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBHeroEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PBHeroEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PBHeroEntity)
        PBHeroEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Hero.internal_static_proto_PBHeroEntity_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 9:
            return internalGetAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 9:
            return internalGetMutableAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Hero.internal_static_proto_PBHeroEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBHeroEntity.class, Builder.class);
      }

      // Construct using proto.Hero.PBHeroEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        heroId_ = 0L;

        confId_ = 0;

        level_ = 0;

        breakLevel_ = 0;

        exp_ = 0;

        awakeInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        awakeLevel_ = 0;

        tianmingLevel_ = 0;

        internalGetMutableAttributes().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Hero.internal_static_proto_PBHeroEntity_descriptor;
      }

      public PBHeroEntity getDefaultInstanceForType() {
        return PBHeroEntity.getDefaultInstance();
      }

      public PBHeroEntity build() {
        PBHeroEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PBHeroEntity buildPartial() {
        PBHeroEntity result = new PBHeroEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.heroId_ = heroId_;
        result.confId_ = confId_;
        result.level_ = level_;
        result.breakLevel_ = breakLevel_;
        result.exp_ = exp_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          awakeInfo_ = java.util.Collections.unmodifiableList(awakeInfo_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.awakeInfo_ = awakeInfo_;
        result.awakeLevel_ = awakeLevel_;
        result.tianmingLevel_ = tianmingLevel_;
        result.attributes_ = internalGetAttributes();
        result.attributes_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBHeroEntity) {
          return mergeFrom((PBHeroEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBHeroEntity other) {
        if (other == PBHeroEntity.getDefaultInstance()) return this;
        if (other.getHeroId() != 0L) {
          setHeroId(other.getHeroId());
        }
        if (other.getConfId() != 0) {
          setConfId(other.getConfId());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getBreakLevel() != 0) {
          setBreakLevel(other.getBreakLevel());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        if (!other.awakeInfo_.isEmpty()) {
          if (awakeInfo_.isEmpty()) {
            awakeInfo_ = other.awakeInfo_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureAwakeInfoIsMutable();
            awakeInfo_.addAll(other.awakeInfo_);
          }
          onChanged();
        }
        if (other.getAwakeLevel() != 0) {
          setAwakeLevel(other.getAwakeLevel());
        }
        if (other.getTianmingLevel() != 0) {
          setTianmingLevel(other.getTianmingLevel());
        }
        internalGetMutableAttributes().mergeFrom(
            other.internalGetAttributes());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBHeroEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBHeroEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long heroId_ ;
      /**
       * <code>optional int64 hero_id = 1;</code>
       */
      public long getHeroId() {
        return heroId_;
      }
      /**
       * <code>optional int64 hero_id = 1;</code>
       */
      public Builder setHeroId(long value) {
        
        heroId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 hero_id = 1;</code>
       */
      public Builder clearHeroId() {
        
        heroId_ = 0L;
        onChanged();
        return this;
      }

      private int confId_ ;
      /**
       * <code>optional int32 conf_id = 2;</code>
       */
      public int getConfId() {
        return confId_;
      }
      /**
       * <code>optional int32 conf_id = 2;</code>
       */
      public Builder setConfId(int value) {
        
        confId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 conf_id = 2;</code>
       */
      public Builder clearConfId() {
        
        confId_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>optional int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 3;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int breakLevel_ ;
      /**
       * <code>optional int32 break_level = 4;</code>
       */
      public int getBreakLevel() {
        return breakLevel_;
      }
      /**
       * <code>optional int32 break_level = 4;</code>
       */
      public Builder setBreakLevel(int value) {
        
        breakLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 break_level = 4;</code>
       */
      public Builder clearBreakLevel() {
        
        breakLevel_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <code>optional int32 exp = 5;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>optional int32 exp = 5;</code>
       */
      public Builder setExp(int value) {
        
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 exp = 5;</code>
       */
      public Builder clearExp() {
        
        exp_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Integer> awakeInfo_ = java.util.Collections.emptyList();
      private void ensureAwakeInfoIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          awakeInfo_ = new java.util.ArrayList<Integer>(awakeInfo_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public java.util.List<Integer>
          getAwakeInfoList() {
        return java.util.Collections.unmodifiableList(awakeInfo_);
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public int getAwakeInfoCount() {
        return awakeInfo_.size();
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public int getAwakeInfo(int index) {
        return awakeInfo_.get(index);
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public Builder setAwakeInfo(
          int index, int value) {
        ensureAwakeInfoIsMutable();
        awakeInfo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public Builder addAwakeInfo(int value) {
        ensureAwakeInfoIsMutable();
        awakeInfo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public Builder addAllAwakeInfo(
          Iterable<? extends Integer> values) {
        ensureAwakeInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, awakeInfo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 awake_info = 6;</code>
       */
      public Builder clearAwakeInfo() {
        awakeInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private int awakeLevel_ ;
      /**
       * <code>optional int32 awake_level = 7;</code>
       */
      public int getAwakeLevel() {
        return awakeLevel_;
      }
      /**
       * <code>optional int32 awake_level = 7;</code>
       */
      public Builder setAwakeLevel(int value) {
        
        awakeLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 awake_level = 7;</code>
       */
      public Builder clearAwakeLevel() {
        
        awakeLevel_ = 0;
        onChanged();
        return this;
      }

      private int tianmingLevel_ ;
      /**
       * <code>optional int32 tianming_level = 8;</code>
       */
      public int getTianmingLevel() {
        return tianmingLevel_;
      }
      /**
       * <code>optional int32 tianming_level = 8;</code>
       */
      public Builder setTianmingLevel(int value) {
        
        tianmingLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tianming_level = 8;</code>
       */
      public Builder clearTianmingLevel() {
        
        tianmingLevel_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          Integer, Integer> attributes_;
      private com.google.protobuf.MapField<Integer, Integer>
      internalGetAttributes() {
        if (attributes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        return attributes_;
      }
      private com.google.protobuf.MapField<Integer, Integer>
      internalGetMutableAttributes() {
        onChanged();;
        if (attributes_ == null) {
          attributes_ = com.google.protobuf.MapField.newMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        if (!attributes_.isMutable()) {
          attributes_ = attributes_.copy();
        }
        return attributes_;
      }

      public int getAttributesCount() {
        return internalGetAttributes().getMap().size();
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */

      public boolean containsAttributes(
          int key) {
        
        return internalGetAttributes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributesMap()} instead.
       */
      @Deprecated
      public java.util.Map<Integer, Integer> getAttributes() {
        return getAttributesMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */

      public java.util.Map<Integer, Integer> getAttributesMap() {
        return internalGetAttributes().getMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */

      public int getAttributesOrDefault(
          int key,
          int defaultValue) {
        
        java.util.Map<Integer, Integer> map =
            internalGetAttributes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */

      public int getAttributesOrThrow(
          int key) {
        
        java.util.Map<Integer, Integer> map =
            internalGetAttributes().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttributes() {
        getMutableAttributes().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */

      public Builder removeAttributes(
          int key) {
        
        getMutableAttributes().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<Integer, Integer>
      getMutableAttributes() {
        return internalGetMutableAttributes().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */
      public Builder putAttributes(
          int key,
          int value) {
        
        
        getMutableAttributes().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; attributes = 9;</code>
       */

      public Builder putAllAttributes(
          java.util.Map<Integer, Integer> values) {
        getMutableAttributes().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PBHeroEntity)
    }

    // @@protoc_insertion_point(class_scope:proto.PBHeroEntity)
    private static final PBHeroEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBHeroEntity();
    }

    public static PBHeroEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBHeroEntity>
        PARSER = new com.google.protobuf.AbstractParser<PBHeroEntity>() {
      public PBHeroEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBHeroEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBHeroEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PBHeroEntity> getParserForType() {
      return PARSER;
    }

    public PBHeroEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PBHeroEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PBHeroEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PBHeroEntity_AttributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PBHeroEntity_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nhero.proto\022\005proto\"\216\002\n\014PBHeroEntity\022\017\n\007" +
      "hero_id\030\001 \001(\003\022\017\n\007conf_id\030\002 \001(\005\022\r\n\005level\030" +
      "\003 \001(\005\022\023\n\013break_level\030\004 \001(\005\022\013\n\003exp\030\005 \001(\005\022" +
      "\022\n\nawake_info\030\006 \003(\005\022\023\n\013awake_level\030\007 \001(\005" +
      "\022\026\n\016tianming_level\030\010 \001(\005\0227\n\nattributes\030\t" +
      " \003(\0132#.proto.PBHeroEntity.AttributesEntr" +
      "y\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005val" +
      "ue\030\002 \001(\005:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_PBHeroEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PBHeroEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PBHeroEntity_descriptor,
        new String[] { "HeroId", "ConfId", "Level", "BreakLevel", "Exp", "AwakeInfo", "AwakeLevel", "TianmingLevel", "Attributes", });
    internal_static_proto_PBHeroEntity_AttributesEntry_descriptor =
      internal_static_proto_PBHeroEntity_descriptor.getNestedTypes().get(0);
    internal_static_proto_PBHeroEntity_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PBHeroEntity_AttributesEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
