// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package proto;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PBLoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PBLoginReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 user_id = 1;</code>
     */
    int getUserId();

    /**
     * <code>optional string token = 2;</code>
     */
    String getToken();
    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code proto.PBLoginReq}
   */
  public  static final class PBLoginReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PBLoginReq)
      PBLoginReqOrBuilder {
    // Use PBLoginReq.newBuilder() to construct.
    private PBLoginReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBLoginReq() {
      userId_ = 0;
      token_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBLoginReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Login.internal_static_proto_PBLoginReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Login.internal_static_proto_PBLoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBLoginReq.class, Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile Object token_;
    /**
     * <code>optional string token = 2;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBLoginReq)) {
        return super.equals(obj);
      }
      PBLoginReq other = (PBLoginReq) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBLoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBLoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBLoginReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PBLoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PBLoginReq)
        PBLoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Login.internal_static_proto_PBLoginReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Login.internal_static_proto_PBLoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBLoginReq.class, Builder.class);
      }

      // Construct using proto.Login.PBLoginReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0;

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Login.internal_static_proto_PBLoginReq_descriptor;
      }

      public PBLoginReq getDefaultInstanceForType() {
        return PBLoginReq.getDefaultInstance();
      }

      public PBLoginReq build() {
        PBLoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PBLoginReq buildPartial() {
        PBLoginReq result = new PBLoginReq(this);
        result.userId_ = userId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBLoginReq) {
          return mergeFrom((PBLoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBLoginReq other) {
        if (other == PBLoginReq.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBLoginReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBLoginReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>optional string token = 2;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PBLoginReq)
    }

    // @@protoc_insertion_point(class_scope:proto.PBLoginReq)
    private static final PBLoginReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBLoginReq();
    }

    public static PBLoginReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBLoginReq>
        PARSER = new com.google.protobuf.AbstractParser<PBLoginReq>() {
      public PBLoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBLoginReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBLoginReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PBLoginReq> getParserForType() {
      return PARSER;
    }

    public PBLoginReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBCreateRoleReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PBCreateRoleReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 gender = 1;</code>
     */
    int getGender();

    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code proto.PBCreateRoleReq}
   */
  public  static final class PBCreateRoleReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PBCreateRoleReq)
      PBCreateRoleReqOrBuilder {
    // Use PBCreateRoleReq.newBuilder() to construct.
    private PBCreateRoleReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBCreateRoleReq() {
      gender_ = 0;
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBCreateRoleReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              gender_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Login.internal_static_proto_PBCreateRoleReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Login.internal_static_proto_PBCreateRoleReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBCreateRoleReq.class, Builder.class);
    }

    public static final int GENDER_FIELD_NUMBER = 1;
    private int gender_;
    /**
     * <code>optional int32 gender = 1;</code>
     */
    public int getGender() {
      return gender_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gender_ != 0) {
        output.writeInt32(1, gender_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, gender_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBCreateRoleReq)) {
        return super.equals(obj);
      }
      PBCreateRoleReq other = (PBCreateRoleReq) obj;

      boolean result = true;
      result = result && (getGender()
          == other.getGender());
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBCreateRoleReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCreateRoleReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCreateRoleReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBCreateRoleReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBCreateRoleReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCreateRoleReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCreateRoleReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBCreateRoleReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBCreateRoleReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBCreateRoleReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBCreateRoleReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PBCreateRoleReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PBCreateRoleReq)
        PBCreateRoleReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Login.internal_static_proto_PBCreateRoleReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Login.internal_static_proto_PBCreateRoleReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBCreateRoleReq.class, Builder.class);
      }

      // Construct using proto.Login.PBCreateRoleReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gender_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Login.internal_static_proto_PBCreateRoleReq_descriptor;
      }

      public PBCreateRoleReq getDefaultInstanceForType() {
        return PBCreateRoleReq.getDefaultInstance();
      }

      public PBCreateRoleReq build() {
        PBCreateRoleReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PBCreateRoleReq buildPartial() {
        PBCreateRoleReq result = new PBCreateRoleReq(this);
        result.gender_ = gender_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBCreateRoleReq) {
          return mergeFrom((PBCreateRoleReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBCreateRoleReq other) {
        if (other == PBCreateRoleReq.getDefaultInstance()) return this;
        if (other.getGender() != 0) {
          setGender(other.getGender());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBCreateRoleReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBCreateRoleReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int gender_ ;
      /**
       * <code>optional int32 gender = 1;</code>
       */
      public int getGender() {
        return gender_;
      }
      /**
       * <code>optional int32 gender = 1;</code>
       */
      public Builder setGender(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gender = 1;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PBCreateRoleReq)
    }

    // @@protoc_insertion_point(class_scope:proto.PBCreateRoleReq)
    private static final PBCreateRoleReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBCreateRoleReq();
    }

    public static PBCreateRoleReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBCreateRoleReq>
        PARSER = new com.google.protobuf.AbstractParser<PBCreateRoleReq>() {
      public PBCreateRoleReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBCreateRoleReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBCreateRoleReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PBCreateRoleReq> getParserForType() {
      return PARSER;
    }

    public PBCreateRoleReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBLoginSuccOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PBLoginSucc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 user_id = 1;</code>
     */
    int getUserId();

    /**
     * <code>optional int64 player_id = 2;</code>
     */
    long getPlayerId();

    /**
     * <code>optional string name = 3;</code>
     */
    String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 tili = 4;</code>
     */
    int getTili();

    /**
     * <code>optional int32 jingli = 5;</code>
     */
    int getJingli();

    /**
     * <code>optional int64 battle_score = 6;</code>
     */
    long getBattleScore();

    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */
    int getResMapCount();
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */
    boolean containsResMap(
			int key);
    /**
     * Use {@link #getResMapMap()} instead.
     */
    @Deprecated
    java.util.Map<Integer, Long>
    getResMap();
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */
    java.util.Map<Integer, Long>
    getResMapMap();
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */

    long getResMapOrDefault(
			int key,
			long defaultValue);
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */

    long getResMapOrThrow(
			int key);

    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    java.util.List<Hero.PBHeroEntity>
        getHeroListList();
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    Hero.PBHeroEntity getHeroList(int index);
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    int getHeroListCount();
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    java.util.List<? extends Hero.PBHeroEntityOrBuilder>
        getHeroListOrBuilderList();
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    Hero.PBHeroEntityOrBuilder getHeroListOrBuilder(
			int index);

    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    java.util.List<proto.Equip.PBEquipEntity> 
        getEquipListList();
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    proto.Equip.PBEquipEntity getEquipList(int index);
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    int getEquipListCount();
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    java.util.List<? extends proto.Equip.PBEquipEntityOrBuilder> 
        getEquipListOrBuilderList();
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    proto.Equip.PBEquipEntityOrBuilder getEquipListOrBuilder(
			int index);
  }
  /**
   * Protobuf type {@code proto.PBLoginSucc}
   */
  public  static final class PBLoginSucc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.PBLoginSucc)
      PBLoginSuccOrBuilder {
    // Use PBLoginSucc.newBuilder() to construct.
    private PBLoginSucc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBLoginSucc() {
      userId_ = 0;
      playerId_ = 0L;
      name_ = "";
      tili_ = 0;
      jingli_ = 0;
      battleScore_ = 0L;
      heroList_ = java.util.Collections.emptyList();
      equipList_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBLoginSucc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 16: {

              playerId_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              tili_ = input.readInt32();
              break;
            }
            case 40: {

              jingli_ = input.readInt32();
              break;
            }
            case 48: {

              battleScore_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                resMap_ = com.google.protobuf.MapField.newMapField(
                    ResMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<Integer, Long>
              resMap__ = input.readMessage(
                  ResMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              resMap_.getMutableMap().put(
                  resMap__.getKey(), resMap__.getValue());
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                heroList_ = new java.util.ArrayList<Hero.PBHeroEntity>();
                mutable_bitField0_ |= 0x00000080;
              }
              heroList_.add(
                  input.readMessage(Hero.PBHeroEntity.parser(), extensionRegistry));
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                equipList_ = new java.util.ArrayList<proto.Equip.PBEquipEntity>();
                mutable_bitField0_ |= 0x00000100;
              }
              equipList_.add(
                  input.readMessage(proto.Equip.PBEquipEntity.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          heroList_ = java.util.Collections.unmodifiableList(heroList_);
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          equipList_ = java.util.Collections.unmodifiableList(equipList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Login.internal_static_proto_PBLoginSucc_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetResMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Login.internal_static_proto_PBLoginSucc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PBLoginSucc.class, Builder.class);
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 user_id = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 2;
    private long playerId_;
    /**
     * <code>optional int64 player_id = 2;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TILI_FIELD_NUMBER = 4;
    private int tili_;
    /**
     * <code>optional int32 tili = 4;</code>
     */
    public int getTili() {
      return tili_;
    }

    public static final int JINGLI_FIELD_NUMBER = 5;
    private int jingli_;
    /**
     * <code>optional int32 jingli = 5;</code>
     */
    public int getJingli() {
      return jingli_;
    }

    public static final int BATTLE_SCORE_FIELD_NUMBER = 6;
    private long battleScore_;
    /**
     * <code>optional int64 battle_score = 6;</code>
     */
    public long getBattleScore() {
      return battleScore_;
    }

    public static final int RES_MAP_FIELD_NUMBER = 7;
    private static final class ResMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          Integer, Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<Integer, Long>newDefaultInstance(
                  Login.internal_static_proto_PBLoginSucc_ResMapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        Integer, Long> resMap_;
    private com.google.protobuf.MapField<Integer, Long>
    internalGetResMap() {
      if (resMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ResMapDefaultEntryHolder.defaultEntry);
      }
      return resMap_;
    }

    public int getResMapCount() {
      return internalGetResMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */

    public boolean containsResMap(
        int key) {
      
      return internalGetResMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getResMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<Integer, Long> getResMap() {
      return getResMapMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */

    public java.util.Map<Integer, Long> getResMapMap() {
      return internalGetResMap().getMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */

    public long getResMapOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<Integer, Long> map =
          internalGetResMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int64&gt; res_map = 7;</code>
     */

    public long getResMapOrThrow(
        int key) {
      
      java.util.Map<Integer, Long> map =
          internalGetResMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int HERO_LIST_FIELD_NUMBER = 8;
    private java.util.List<Hero.PBHeroEntity> heroList_;
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    public java.util.List<Hero.PBHeroEntity> getHeroListList() {
      return heroList_;
    }
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    public java.util.List<? extends Hero.PBHeroEntityOrBuilder>
        getHeroListOrBuilderList() {
      return heroList_;
    }
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    public int getHeroListCount() {
      return heroList_.size();
    }
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    public Hero.PBHeroEntity getHeroList(int index) {
      return heroList_.get(index);
    }
    /**
     * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
     */
    public Hero.PBHeroEntityOrBuilder getHeroListOrBuilder(
        int index) {
      return heroList_.get(index);
    }

    public static final int EQUIP_LIST_FIELD_NUMBER = 9;
    private java.util.List<proto.Equip.PBEquipEntity> equipList_;
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    public java.util.List<proto.Equip.PBEquipEntity> getEquipListList() {
      return equipList_;
    }
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    public java.util.List<? extends proto.Equip.PBEquipEntityOrBuilder> 
        getEquipListOrBuilderList() {
      return equipList_;
    }
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    public int getEquipListCount() {
      return equipList_.size();
    }
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    public proto.Equip.PBEquipEntity getEquipList(int index) {
      return equipList_.get(index);
    }
    /**
     * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
     */
    public proto.Equip.PBEquipEntityOrBuilder getEquipListOrBuilder(
        int index) {
      return equipList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (playerId_ != 0L) {
        output.writeInt64(2, playerId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (tili_ != 0) {
        output.writeInt32(4, tili_);
      }
      if (jingli_ != 0) {
        output.writeInt32(5, jingli_);
      }
      if (battleScore_ != 0L) {
        output.writeInt64(6, battleScore_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetResMap(),
          ResMapDefaultEntryHolder.defaultEntry,
          7);
      for (int i = 0; i < heroList_.size(); i++) {
        output.writeMessage(8, heroList_.get(i));
      }
      for (int i = 0; i < equipList_.size(); i++) {
        output.writeMessage(9, equipList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (tili_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tili_);
      }
      if (jingli_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, jingli_);
      }
      if (battleScore_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, battleScore_);
      }
      for (java.util.Map.Entry<Integer, Long> entry
           : internalGetResMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<Integer, Long>
        resMap__ = ResMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, resMap__);
      }
      for (int i = 0; i < heroList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, heroList_.get(i));
      }
      for (int i = 0; i < equipList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, equipList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PBLoginSucc)) {
        return super.equals(obj);
      }
      PBLoginSucc other = (PBLoginSucc) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getTili()
          == other.getTili());
      result = result && (getJingli()
          == other.getJingli());
      result = result && (getBattleScore()
          == other.getBattleScore());
      result = result && internalGetResMap().equals(
          other.internalGetResMap());
      result = result && getHeroListList()
          .equals(other.getHeroListList());
      result = result && getEquipListList()
          .equals(other.getEquipListList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TILI_FIELD_NUMBER;
      hash = (53 * hash) + getTili();
      hash = (37 * hash) + JINGLI_FIELD_NUMBER;
      hash = (53 * hash) + getJingli();
      hash = (37 * hash) + BATTLE_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBattleScore());
      if (!internalGetResMap().getMap().isEmpty()) {
        hash = (37 * hash) + RES_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetResMap().hashCode();
      }
      if (getHeroListCount() > 0) {
        hash = (37 * hash) + HERO_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getHeroListList().hashCode();
      }
      if (getEquipListCount() > 0) {
        hash = (37 * hash) + EQUIP_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getEquipListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PBLoginSucc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLoginSucc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLoginSucc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PBLoginSucc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PBLoginSucc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLoginSucc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLoginSucc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PBLoginSucc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PBLoginSucc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PBLoginSucc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PBLoginSucc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PBLoginSucc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PBLoginSucc)
        PBLoginSuccOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Login.internal_static_proto_PBLoginSucc_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetResMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableResMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Login.internal_static_proto_PBLoginSucc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PBLoginSucc.class, Builder.class);
      }

      // Construct using proto.Login.PBLoginSucc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeroListFieldBuilder();
          getEquipListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0;

        playerId_ = 0L;

        name_ = "";

        tili_ = 0;

        jingli_ = 0;

        battleScore_ = 0L;

        internalGetMutableResMap().clear();
        if (heroListBuilder_ == null) {
          heroList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          heroListBuilder_.clear();
        }
        if (equipListBuilder_ == null) {
          equipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          equipListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Login.internal_static_proto_PBLoginSucc_descriptor;
      }

      public PBLoginSucc getDefaultInstanceForType() {
        return PBLoginSucc.getDefaultInstance();
      }

      public PBLoginSucc build() {
        PBLoginSucc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PBLoginSucc buildPartial() {
        PBLoginSucc result = new PBLoginSucc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.userId_ = userId_;
        result.playerId_ = playerId_;
        result.name_ = name_;
        result.tili_ = tili_;
        result.jingli_ = jingli_;
        result.battleScore_ = battleScore_;
        result.resMap_ = internalGetResMap();
        result.resMap_.makeImmutable();
        if (heroListBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            heroList_ = java.util.Collections.unmodifiableList(heroList_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.heroList_ = heroList_;
        } else {
          result.heroList_ = heroListBuilder_.build();
        }
        if (equipListBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            equipList_ = java.util.Collections.unmodifiableList(equipList_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.equipList_ = equipList_;
        } else {
          result.equipList_ = equipListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBLoginSucc) {
          return mergeFrom((PBLoginSucc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PBLoginSucc other) {
        if (other == PBLoginSucc.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getTili() != 0) {
          setTili(other.getTili());
        }
        if (other.getJingli() != 0) {
          setJingli(other.getJingli());
        }
        if (other.getBattleScore() != 0L) {
          setBattleScore(other.getBattleScore());
        }
        internalGetMutableResMap().mergeFrom(
            other.internalGetResMap());
        if (heroListBuilder_ == null) {
          if (!other.heroList_.isEmpty()) {
            if (heroList_.isEmpty()) {
              heroList_ = other.heroList_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureHeroListIsMutable();
              heroList_.addAll(other.heroList_);
            }
            onChanged();
          }
        } else {
          if (!other.heroList_.isEmpty()) {
            if (heroListBuilder_.isEmpty()) {
              heroListBuilder_.dispose();
              heroListBuilder_ = null;
              heroList_ = other.heroList_;
              bitField0_ = (bitField0_ & ~0x00000080);
              heroListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeroListFieldBuilder() : null;
            } else {
              heroListBuilder_.addAllMessages(other.heroList_);
            }
          }
        }
        if (equipListBuilder_ == null) {
          if (!other.equipList_.isEmpty()) {
            if (equipList_.isEmpty()) {
              equipList_ = other.equipList_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureEquipListIsMutable();
              equipList_.addAll(other.equipList_);
            }
            onChanged();
          }
        } else {
          if (!other.equipList_.isEmpty()) {
            if (equipListBuilder_.isEmpty()) {
              equipListBuilder_.dispose();
              equipListBuilder_ = null;
              equipList_ = other.equipList_;
              bitField0_ = (bitField0_ & ~0x00000100);
              equipListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEquipListFieldBuilder() : null;
            } else {
              equipListBuilder_.addAllMessages(other.equipList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PBLoginSucc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PBLoginSucc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>optional int64 player_id = 2;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 player_id = 2;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 player_id = 2;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int tili_ ;
      /**
       * <code>optional int32 tili = 4;</code>
       */
      public int getTili() {
        return tili_;
      }
      /**
       * <code>optional int32 tili = 4;</code>
       */
      public Builder setTili(int value) {
        
        tili_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tili = 4;</code>
       */
      public Builder clearTili() {
        
        tili_ = 0;
        onChanged();
        return this;
      }

      private int jingli_ ;
      /**
       * <code>optional int32 jingli = 5;</code>
       */
      public int getJingli() {
        return jingli_;
      }
      /**
       * <code>optional int32 jingli = 5;</code>
       */
      public Builder setJingli(int value) {
        
        jingli_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 jingli = 5;</code>
       */
      public Builder clearJingli() {
        
        jingli_ = 0;
        onChanged();
        return this;
      }

      private long battleScore_ ;
      /**
       * <code>optional int64 battle_score = 6;</code>
       */
      public long getBattleScore() {
        return battleScore_;
      }
      /**
       * <code>optional int64 battle_score = 6;</code>
       */
      public Builder setBattleScore(long value) {
        
        battleScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 battle_score = 6;</code>
       */
      public Builder clearBattleScore() {
        
        battleScore_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          Integer, Long> resMap_;
      private com.google.protobuf.MapField<Integer, Long>
      internalGetResMap() {
        if (resMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ResMapDefaultEntryHolder.defaultEntry);
        }
        return resMap_;
      }
      private com.google.protobuf.MapField<Integer, Long>
      internalGetMutableResMap() {
        onChanged();;
        if (resMap_ == null) {
          resMap_ = com.google.protobuf.MapField.newMapField(
              ResMapDefaultEntryHolder.defaultEntry);
        }
        if (!resMap_.isMutable()) {
          resMap_ = resMap_.copy();
        }
        return resMap_;
      }

      public int getResMapCount() {
        return internalGetResMap().getMap().size();
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */

      public boolean containsResMap(
          int key) {
        
        return internalGetResMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getResMapMap()} instead.
       */
      @Deprecated
      public java.util.Map<Integer, Long> getResMap() {
        return getResMapMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */

      public java.util.Map<Integer, Long> getResMapMap() {
        return internalGetResMap().getMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */

      public long getResMapOrDefault(
          int key,
          long defaultValue) {
        
        java.util.Map<Integer, Long> map =
            internalGetResMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */

      public long getResMapOrThrow(
          int key) {
        
        java.util.Map<Integer, Long> map =
            internalGetResMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearResMap() {
        getMutableResMap().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */

      public Builder removeResMap(
          int key) {
        
        getMutableResMap().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<Integer, Long>
      getMutableResMap() {
        return internalGetMutableResMap().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */
      public Builder putResMap(
          int key,
          long value) {
        
        
        getMutableResMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; res_map = 7;</code>
       */

      public Builder putAllResMap(
          java.util.Map<Integer, Long> values) {
        getMutableResMap().putAll(values);
        return this;
      }

      private java.util.List<Hero.PBHeroEntity> heroList_ =
        java.util.Collections.emptyList();
      private void ensureHeroListIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          heroList_ = new java.util.ArrayList<Hero.PBHeroEntity>(heroList_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Hero.PBHeroEntity, Hero.PBHeroEntity.Builder, Hero.PBHeroEntityOrBuilder> heroListBuilder_;

      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public java.util.List<Hero.PBHeroEntity> getHeroListList() {
        if (heroListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(heroList_);
        } else {
          return heroListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public int getHeroListCount() {
        if (heroListBuilder_ == null) {
          return heroList_.size();
        } else {
          return heroListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Hero.PBHeroEntity getHeroList(int index) {
        if (heroListBuilder_ == null) {
          return heroList_.get(index);
        } else {
          return heroListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder setHeroList(
          int index, Hero.PBHeroEntity value) {
        if (heroListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroListIsMutable();
          heroList_.set(index, value);
          onChanged();
        } else {
          heroListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder setHeroList(
          int index, Hero.PBHeroEntity.Builder builderForValue) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.set(index, builderForValue.build());
          onChanged();
        } else {
          heroListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder addHeroList(Hero.PBHeroEntity value) {
        if (heroListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroListIsMutable();
          heroList_.add(value);
          onChanged();
        } else {
          heroListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder addHeroList(
          int index, Hero.PBHeroEntity value) {
        if (heroListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroListIsMutable();
          heroList_.add(index, value);
          onChanged();
        } else {
          heroListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder addHeroList(
          Hero.PBHeroEntity.Builder builderForValue) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.add(builderForValue.build());
          onChanged();
        } else {
          heroListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder addHeroList(
          int index, Hero.PBHeroEntity.Builder builderForValue) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.add(index, builderForValue.build());
          onChanged();
        } else {
          heroListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder addAllHeroList(
          Iterable<? extends Hero.PBHeroEntity> values) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, heroList_);
          onChanged();
        } else {
          heroListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder clearHeroList() {
        if (heroListBuilder_ == null) {
          heroList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          heroListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Builder removeHeroList(int index) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.remove(index);
          onChanged();
        } else {
          heroListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Hero.PBHeroEntity.Builder getHeroListBuilder(
          int index) {
        return getHeroListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Hero.PBHeroEntityOrBuilder getHeroListOrBuilder(
          int index) {
        if (heroListBuilder_ == null) {
          return heroList_.get(index);  } else {
          return heroListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public java.util.List<? extends Hero.PBHeroEntityOrBuilder>
           getHeroListOrBuilderList() {
        if (heroListBuilder_ != null) {
          return heroListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(heroList_);
        }
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Hero.PBHeroEntity.Builder addHeroListBuilder() {
        return getHeroListFieldBuilder().addBuilder(
            Hero.PBHeroEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public Hero.PBHeroEntity.Builder addHeroListBuilder(
          int index) {
        return getHeroListFieldBuilder().addBuilder(
            index, Hero.PBHeroEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PBHeroEntity hero_list = 8;</code>
       */
      public java.util.List<Hero.PBHeroEntity.Builder>
           getHeroListBuilderList() {
        return getHeroListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Hero.PBHeroEntity, Hero.PBHeroEntity.Builder, Hero.PBHeroEntityOrBuilder>
          getHeroListFieldBuilder() {
        if (heroListBuilder_ == null) {
          heroListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Hero.PBHeroEntity, Hero.PBHeroEntity.Builder, Hero.PBHeroEntityOrBuilder>(
                  heroList_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          heroList_ = null;
        }
        return heroListBuilder_;
      }

      private java.util.List<proto.Equip.PBEquipEntity> equipList_ =
        java.util.Collections.emptyList();
      private void ensureEquipListIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          equipList_ = new java.util.ArrayList<proto.Equip.PBEquipEntity>(equipList_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Equip.PBEquipEntity, proto.Equip.PBEquipEntity.Builder, proto.Equip.PBEquipEntityOrBuilder> equipListBuilder_;

      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public java.util.List<proto.Equip.PBEquipEntity> getEquipListList() {
        if (equipListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(equipList_);
        } else {
          return equipListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public int getEquipListCount() {
        if (equipListBuilder_ == null) {
          return equipList_.size();
        } else {
          return equipListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public proto.Equip.PBEquipEntity getEquipList(int index) {
        if (equipListBuilder_ == null) {
          return equipList_.get(index);
        } else {
          return equipListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder setEquipList(
          int index, proto.Equip.PBEquipEntity value) {
        if (equipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipListIsMutable();
          equipList_.set(index, value);
          onChanged();
        } else {
          equipListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder setEquipList(
          int index, proto.Equip.PBEquipEntity.Builder builderForValue) {
        if (equipListBuilder_ == null) {
          ensureEquipListIsMutable();
          equipList_.set(index, builderForValue.build());
          onChanged();
        } else {
          equipListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder addEquipList(proto.Equip.PBEquipEntity value) {
        if (equipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipListIsMutable();
          equipList_.add(value);
          onChanged();
        } else {
          equipListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder addEquipList(
          int index, proto.Equip.PBEquipEntity value) {
        if (equipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipListIsMutable();
          equipList_.add(index, value);
          onChanged();
        } else {
          equipListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder addEquipList(
          proto.Equip.PBEquipEntity.Builder builderForValue) {
        if (equipListBuilder_ == null) {
          ensureEquipListIsMutable();
          equipList_.add(builderForValue.build());
          onChanged();
        } else {
          equipListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder addEquipList(
          int index, proto.Equip.PBEquipEntity.Builder builderForValue) {
        if (equipListBuilder_ == null) {
          ensureEquipListIsMutable();
          equipList_.add(index, builderForValue.build());
          onChanged();
        } else {
          equipListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder addAllEquipList(
          Iterable<? extends proto.Equip.PBEquipEntity> values) {
        if (equipListBuilder_ == null) {
          ensureEquipListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, equipList_);
          onChanged();
        } else {
          equipListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder clearEquipList() {
        if (equipListBuilder_ == null) {
          equipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          equipListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public Builder removeEquipList(int index) {
        if (equipListBuilder_ == null) {
          ensureEquipListIsMutable();
          equipList_.remove(index);
          onChanged();
        } else {
          equipListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public proto.Equip.PBEquipEntity.Builder getEquipListBuilder(
          int index) {
        return getEquipListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public proto.Equip.PBEquipEntityOrBuilder getEquipListOrBuilder(
          int index) {
        if (equipListBuilder_ == null) {
          return equipList_.get(index);  } else {
          return equipListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public java.util.List<? extends proto.Equip.PBEquipEntityOrBuilder> 
           getEquipListOrBuilderList() {
        if (equipListBuilder_ != null) {
          return equipListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(equipList_);
        }
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public proto.Equip.PBEquipEntity.Builder addEquipListBuilder() {
        return getEquipListFieldBuilder().addBuilder(
            proto.Equip.PBEquipEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public proto.Equip.PBEquipEntity.Builder addEquipListBuilder(
          int index) {
        return getEquipListFieldBuilder().addBuilder(
            index, proto.Equip.PBEquipEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.PBEquipEntity equip_list = 9;</code>
       */
      public java.util.List<proto.Equip.PBEquipEntity.Builder> 
           getEquipListBuilderList() {
        return getEquipListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Equip.PBEquipEntity, proto.Equip.PBEquipEntity.Builder, proto.Equip.PBEquipEntityOrBuilder> 
          getEquipListFieldBuilder() {
        if (equipListBuilder_ == null) {
          equipListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.Equip.PBEquipEntity, proto.Equip.PBEquipEntity.Builder, proto.Equip.PBEquipEntityOrBuilder>(
                  equipList_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          equipList_ = null;
        }
        return equipListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PBLoginSucc)
    }

    // @@protoc_insertion_point(class_scope:proto.PBLoginSucc)
    private static final PBLoginSucc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PBLoginSucc();
    }

    public static PBLoginSucc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBLoginSucc>
        PARSER = new com.google.protobuf.AbstractParser<PBLoginSucc>() {
      public PBLoginSucc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBLoginSucc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBLoginSucc> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PBLoginSucc> getParserForType() {
      return PARSER;
    }

    public PBLoginSucc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PBLoginReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PBLoginReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PBCreateRoleReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PBCreateRoleReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PBLoginSucc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PBLoginSucc_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PBLoginSucc_ResMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PBLoginSucc_ResMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013login.proto\022\005proto\032\nhero.proto\032\013equip." +
      "proto\",\n\nPBLoginReq\022\017\n\007user_id\030\001 \001(\005\022\r\n\005" +
      "token\030\002 \001(\t\"/\n\017PBCreateRoleReq\022\016\n\006gender" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"\245\002\n\013PBLoginSucc\022\017\n\007" +
      "user_id\030\001 \001(\005\022\021\n\tplayer_id\030\002 \001(\003\022\014\n\004name" +
      "\030\003 \001(\t\022\014\n\004tili\030\004 \001(\005\022\016\n\006jingli\030\005 \001(\005\022\024\n\014" +
      "battle_score\030\006 \001(\003\022/\n\007res_map\030\007 \003(\0132\036.pr" +
      "oto.PBLoginSucc.ResMapEntry\022&\n\thero_list" +
      "\030\010 \003(\0132\023.proto.PBHeroEntity\022(\n\nequip_lis" +
      "t\030\t \003(\0132\024.proto.PBEquipEntity\032-\n\013ResMapE",
      "ntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\003:\0028\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Hero.getDescriptor(),
          proto.Equip.getDescriptor(),
        }, assigner);
    internal_static_proto_PBLoginReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PBLoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PBLoginReq_descriptor,
        new String[] { "UserId", "Token", });
    internal_static_proto_PBCreateRoleReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_PBCreateRoleReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PBCreateRoleReq_descriptor,
        new String[] { "Gender", "Name", });
    internal_static_proto_PBLoginSucc_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_PBLoginSucc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PBLoginSucc_descriptor,
        new String[] { "UserId", "PlayerId", "Name", "Tili", "Jingli", "BattleScore", "ResMap", "HeroList", "EquipList", });
    internal_static_proto_PBLoginSucc_ResMapEntry_descriptor =
      internal_static_proto_PBLoginSucc_descriptor.getNestedTypes().get(0);
    internal_static_proto_PBLoginSucc_ResMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PBLoginSucc_ResMapEntry_descriptor,
        new String[] { "Key", "Value", });
    Hero.getDescriptor();
    proto.Equip.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
